# Image de base
FROM php:8.2-apache

# Configuration du répertoire de travail
WORKDIR /var/www/html

# Copie du fichier index.php
COPY index.php /var/www/html/

# Configuration des permissions
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Exposition du port 80
EXPOSE 80

# Commande par défaut pour démarrer Apache
CMD ["apache2-foreground"] 