version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projetdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: node_backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: projetdb
    networks:
      - app_network

  nginx:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer_db
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: 